@startuml
start

:Старт;
:Сделать заказ;
:Номер стола, имя клиента,\nномер телефона;
:Создание счёта;

while (Добавить позицию?) is (да)
  :Блюдо, количество, цена;
  :Меню;
  :Позиция;

  while (Убрать позицию?) is (да)
    :Позиция;
  endwhile
endwhile

:Оформление заказа;
:Итоговый счёт;
:Конец;

@enduml